name: CI

#on:
#  push:
#    tags:
#      - "*.*.*"
on:
  push:
    branches:
      - main

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Downloads artifacts
        run: |
          ls -la
          "export RELEASE_VERSION=$(cat src/helpers/__version__.py | awk -F\"__version__ =\" {'print \$2'} | tr -d \'[\"'\\'' '^',]\')"
          echo "Name ${{ github.ref_name }}. Version $RELEASE_VERSION"
          touch test.txt

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/$RELEASE_VERSION>',
              sha: context.sha
            })

#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          name: ${{ github.ref_name }}
#          body: Release $RELEASE_VERSION
#          prerelease: false
#          draft: false
#          make_latest: true
#          with:
#            files: |
#              "test.txt"
